# Generated by Django 5.2.7 on 2025-10-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stamp_image', models.ImageField(upload_to='pdf_stamps/')),
                ('signature_image', models.ImageField(upload_to='pdf_signatures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_address', models.TextField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_address', models.TextField()),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('current_location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked by Courier'), ('on_hold', 'On Hold'), ('on_way', 'On the Way'), ('custom_hold', 'Custom Hold'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('parcel_description', models.TextField(blank=True, null=True)),
                ('parcel_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parcel_image', models.ImageField(blank=True, null=True, upload_to='parcel_images/')),
                ('require_payment', models.BooleanField(default=False)),
                ('show_payment_info', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('usdt', 'USDT (Tether)')], default='bitcoin', max_length=20)),
                ('shipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clearance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crypto_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid')], default='not_required', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.shipment')),
            ],
        ),
    ]
