# Generated by Django 5.2.7 on 2025-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GlobalTrack Pro', max_length=200)),
                ('company_name', models.CharField(default='GlobalTrack Pro', max_length=200)),
                ('contact_email', models.EmailField(default='support@globaltrackpro.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('company_address', models.TextField(default='Global Headquarters')),
                ('website_url', models.URLField(default='https://globaltrackpro.com')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('pdf_header_title', models.CharField(default='SHIPMENT TRACKING REPORT', max_length=200)),
                ('pdf_footer_text', models.TextField(default='Generated by GlobalTrack Pro - Professional Shipping Solutions')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
